In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression, SGDClassifier
from mlxtend.plotting import plot_decision_regions
from sklearn.utils import shuffle

In [2]:
!pip install --upgrade --no-cache-dir gdown
!gdown 1Won6xkyYCcJLJ7eMpVt5VA_4P0tE1nb7

  Attempting uninstall: gdown
    Found existing installation: gdown 4.7.3
    Uninstalling gdown-4.7.3:
      Successfully uninstalled gdown-4.7.3
Downloading...
From: https://drive.google.com/uc?id=1Won6xkyYCcJLJ7eMpVt5VA_4P0tE1nb7
To: /content/data_banknote_authentication.txt
100% 46.4k/46.4k [00:00<00:00, 117MB/s]


In [3]:
df = pd.read_csv('/content/data_banknote_authentication.txt')
df

x1        x2       x3       x4  y
0     3.62160   8.66610  -2.8073 -0.44699  0
1     4.54590   8.16740  -2.4586 -1.46210  0
2     3.86600  -2.63830   1.9242  0.10645  0
3     3.45660   9.52280  -4.0112 -3.59440  0
4     0.32924  -4.45520   4.5718 -0.98880  0
...       ...       ...      ...      ... ..
1367  0.40614   1.34920  -1.4501 -0.55949  1
1368 -1.38870  -4.87730   6.4774  0.34179  1
1369 -3.75030 -13.45860  17.5932 -2.77710  1
1370 -3.56370  -8.38270  12.3930 -1.28230  1
1371 -2.54190  -0.65804   2.6842  1.19520  1

[1372 rows x 5 columns]

In [4]:
shuffled_data = shuffle(df)
shuffled_data.to_csv('created_data.csv', index=False)
print(shuffled_data)

           x1         x2       x3       x4  y
69    0.12326   8.984800 -0.93510 -2.43320  0
31    1.48840   3.627400  3.30800  0.48921  0
1010 -2.99150  -6.625800  8.65210  1.81980  1
1316 -1.60290  -0.389030  1.62000  1.91030  1
35    2.43910   6.441700 -0.80743 -0.69139  0
...       ...        ...      ...      ... ..
343   0.66018  10.387800 -1.40290 -3.91510  0
1106 -0.12690  -1.150500 -0.95138  0.57843  1
1341 -2.26250  -0.099335  2.81270  0.48662  1
303  -1.91770  11.689400  2.54540 -3.27630  0
1147 -1.69880  -7.116300  5.79020  0.16723  1

[1372 rows x 5 columns]


In [5]:
df2 = pd.read_csv('/content/created_data.csv')
df2

x1         x2       x3       x4  y
0     0.12326   8.984800 -0.93510 -2.43320  0
1     1.48840   3.627400  3.30800  0.48921  0
2    -2.99150  -6.625800  8.65210  1.81980  1
3    -1.60290  -0.389030  1.62000  1.91030  1
4     2.43910   6.441700 -0.80743 -0.69139  0
...       ...        ...      ...      ... ..
1367  0.66018  10.387800 -1.40290 -3.91510  0
1368 -0.12690  -1.150500 -0.95138  0.57843  1
1369 -2.26250  -0.099335  2.81270  0.48662  1
1370 -1.91770  11.689400  2.54540 -3.27630  0
1371 -1.69880  -7.116300  5.79020  0.16723  1

[1372 rows x 5 columns]

In [6]:
class_counts = df2['y'].value_counts()

# نمایش تعداد نمونه‌ها برای هر کلاس
print(class_counts)

0    762
1    610
Name: y, dtype: int64


In [7]:
X = df2[['x1','x2','x3','x4']].values
y = df2[['y']].values
X, y

(array([[ 0.12326 ,  8.9848  , -0.9351  , -2.4332  ],
        [ 1.4884  ,  3.6274  ,  3.308   ,  0.48921 ],
        [-2.9915  , -6.6258  ,  8.6521  ,  1.8198  ],
        ...,
        [-2.2625  , -0.099335,  2.8127  ,  0.48662 ],
        [-1.9177  , 11.6894  ,  2.5454  , -3.2763  ],
        [-1.6988  , -7.1163  ,  5.7902  ,  0.16723 ]]),
 array([[0],
        [0],
        [1],
        ...,
        [1],
        [0],
        [1]]))

In [9]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)
model = LogisticRegression(solver='sag',class_weight='balanced', max_iter=60000, random_state=42)
history=model.fit(x_train, y_train)
print(x_train.shape), print(y_train.shape), print(x_test.shape), print(y_test.shape)
y_pred=model.predict(x_test)
y_pred, y_test

(1097, 4)
(1097, 1)
(275, 4)
(275, 1)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(array([1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
        0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1]),
 array([[1],
        [0],
        [1],
        [1],
        [1],
    

In [ ]:

model.score(x_train, y_train)

0.995

In [ ]:
model.score(x_test, y_test)

0.995